### ISSUE TITLE
Text color

### ISSUE THREAD

**Issue by maitrey-credencys9** [michaelmuenzer/ScrollableNumberPicker#5]
Text color is not getting changed
I have passed color in all possible different ways in xml :
 numberpicker:snp_value_text_color="#fff"
 numberpicker:snp_value_text_color="#ffffff"
 numberpicker:snp_value_text_color="@android:color/white"
 numberpicker:snp_value_text_color="@color/white"

could not set text color in java file

**Comment by michaelmuenzer** [comment]
Thank you for the feedback, that is obviously a bug. I fixed it within db4f423e0192f9850da4ea96a96f34ea3786c9c0
