### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by tigpalmas** [michaelmuenzer/ScrollableNumberPicker#8]
is it possible to change the icons size ? att

**Comment by michaelmuenzer** [comment]
There is no specific xml-attribute for doing that, but you can change the drawables you are using to achieve this. So you could e.g. change `android:width` and `android:height` in `arrow_up_bold_circle_outline.xml`. 

With the help of `app:snp_buttonTouchScaleFactor` you can also change the size when the user presses one of the buttons.
